name: Python application test with GitHub Actions
# run-name: ${{ github.actor }} workflow test

on:
   push:
       branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2  # Fetch the last a two commits. You can adjust this as needed.a

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Replace this with the version of Python you're using.

    - name : Install Packages 
      run : pip install pytest

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        # If you need additional dependencies for tests you can install them here.

    - name: Run tests
      run: python -m unittest discover
      

    - name: Run tests
      run: |
        # Add the command to run your tests. For example:
        python -m unittest ./Test/test_unit.py